language: node_js

node_js:
  - "0.10"
  # tests failing for unknown reasons
  #- "4"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        postgresql: "9.5"
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++6 # upgrade libstdc++ on linux to support C++11
           - libwebkit-dev
           - postgresql-9.5-postgis-2.3
    - os: osx
      osx_image: xcode7.3

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -w -s -D /usr/local/var/postgres start; fi
 - createdb template_postgis
 - psql -c "CREATE EXTENSION postgis" template_postgis

install:
- npm install --fallback-to-build=false
- python test/check_shared_libs.py node_modules/

before_script:
 - npm ls

script:
 - npm test
 - [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd platforms/osx; make; fi
